import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const palSnapshotFetchGuard = `
(() => {
  const originalFetch = window.fetch.bind(window);
  let cachedSnapshot = null;
  let inFlightSnapshot = null;

  window.fetch = async function guardedFetch(input, init) {
    const url =
      typeof input === "string"
        ? input
        : input instanceof Request
          ? input.url
          : String(input);

    const method = (
      init?.method ??
      (input instanceof Request ? input.method : "GET")
    ).toUpperCase();

    const isPalSnapshot =
      method === "GET" &&
      /\\/api\\/pal-snapshot(?:\\?|$)/.test(url);

    if (!isPalSnapshot) {
      return originalFetch(input, init);
    }

    if (cachedSnapshot) {
      return cachedSnapshot.clone();
    }

    if (inFlightSnapshot) {
      const response = await inFlightSnapshot;
      return response.clone();
    }

    inFlightSnapshot = originalFetch(input, init)
      .then((response) => {
        if (response.ok) {
          cachedSnapshot = response.clone();
        }
        return response;
      })
      .finally(() => {
        inFlightSnapshot = null;
      });

    const response = await inFlightSnapshot;
    return response.clone();
  };
})();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: palSnapshotFetchGuard,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
